dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.12
env:
- GO111MODULE=on

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh

script:
- make test
- make vet
- make website-test
- docker-compose run --rm setup
# run test using custom root CA
- PDNS_SERVER_URL=localhost:4443 PDNS_API_KEY=secret PDNS_CACERT="$PWD/tests/files/ssl/rootCA/rootCA.crt" make testacc
# run test skipping TLS verification (Insecure HTTPS)
- PDNS_SERVER_URL=localhost:4443 PDNS_API_KEY=secret PDNS_INSECURE_HTTPS=true make testacc
- docker-compose down

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
